/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateEntryArgs } from "./CreateEntryArgs";
import { UpdateEntryArgs } from "./UpdateEntryArgs";
import { DeleteEntryArgs } from "./DeleteEntryArgs";
import { EntryFindManyArgs } from "./EntryFindManyArgs";
import { EntryFindUniqueArgs } from "./EntryFindUniqueArgs";
import { Entry } from "./Entry";
import { EntryService } from "../entry.service";

@graphql.Resolver(() => Entry)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class EntryResolverBase {
  constructor(
    protected readonly service: EntryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Entry",
    action: "read",
    possession: "any",
  })
  async _entriesMeta(
    @graphql.Args() args: EntryFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Entry])
  @nestAccessControl.UseRoles({
    resource: "Entry",
    action: "read",
    possession: "any",
  })
  async entries(@graphql.Args() args: EntryFindManyArgs): Promise<Entry[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Entry, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Entry",
    action: "read",
    possession: "own",
  })
  async entry(
    @graphql.Args() args: EntryFindUniqueArgs
  ): Promise<Entry | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Entry)
  @nestAccessControl.UseRoles({
    resource: "Entry",
    action: "create",
    possession: "any",
  })
  async createEntry(@graphql.Args() args: CreateEntryArgs): Promise<Entry> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Entry)
  @nestAccessControl.UseRoles({
    resource: "Entry",
    action: "update",
    possession: "any",
  })
  async updateEntry(
    @graphql.Args() args: UpdateEntryArgs
  ): Promise<Entry | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Entry)
  @nestAccessControl.UseRoles({
    resource: "Entry",
    action: "delete",
    possession: "any",
  })
  async deleteEntry(
    @graphql.Args() args: DeleteEntryArgs
  ): Promise<Entry | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
